/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.ac.uniska.ui;

import id.ac.uniska.helper.MyConnection;
import id.ac.uniska.model.MataKuliah;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author ASUS
 */
public class MataKuliahRead extends javax.swing.JFrame {

    /**
     * Creates new form MataKuliahRead
     */
    public MataKuliahRead() {
        initComponents();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        matakuliahTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        matakuliahTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID MATAKULIAH", "NAMA MATAKULIAH", "SINGKATAN MATAKULIAH", "NAMA DOSEN", "KONTAK DOSEN", "AKTIF"
            }
        ));
        jScrollPane1.setViewportView(matakuliahTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(567, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     * @throws java.sql.SQLException
     */
 public static void main(String args[]) throws SQLException {
     
    MataKuliahRead mataKuliahRead = new MataKuliahRead();
    mataKuliahRead.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    mataKuliahRead.createUIComponents();
    mataKuliahRead.pack();
    mataKuliahRead.setLocationRelativeTo(null);
    mataKuliahRead.setVisible(true);
    
  
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MataKuliahRead.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
     /* java.awt.EventQueue.invokeLater(new Runnable() {
           public void run() {
               new MataKuliahRead().setVisible(true);
            }
       }); */
    }  


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable matakuliahTable;
    // End of variables declaration//GEN-END:variables
  private void createUIComponents() throws SQLException{
    MataKuliah mataKuliah;
    ArrayList<MataKuliah> mataKuliahArrayList = new ArrayList<>();
    MyConnection myConnection = new MyConnection();
    Connection con = myConnection.getConnection();
    
    String selectQuery = "SELECT * FROM makul";
     Statement statement;
     ResultSet resultSet;
    
    try{
        statement = con.createStatement();
        resultSet = statement.executeQuery(selectQuery);
        while (resultSet.next())
        {
            mataKuliah = new MataKuliah(
                    resultSet.getInt("id_makul"),
                    resultSet.getString("nama_makul"),
                    resultSet.getString("singkatan_makul"),
                    resultSet.getString("nama_dosen"),
                    resultSet.getString("kontak_dosen"),
                    resultSet.getBoolean("aktif")        
            );
                        mataKuliahArrayList.add(mataKuliah);
              }
          }catch (SQLException e)
          {
              e.printStackTrace();
    }
     DefaultTableModel dtm = (DefaultTableModel) matakuliahTable.getModel();
        dtm.setRowCount(0);
        Object [] row = new Object[6];
       int i = 1;
       for (MataKuliah value : mataKuliahArrayList){
        
        row [0] = value.getIdMakul();
        row [1] = value.getNamaMakul();
        row [2] = value.getSingkatanMakul();
        row [3] = value.getNamaDosen();
        row [4] = value.getKontakDosen();
        row [5] = value.isAktif();

          dtm.addRow(row);
            i++;
      }
    }
}
